// This file will be auto-generated by Supabase, but we'll define a basic structure
export type Database = {
  public: {
    Tables: {
      products: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          price: number;
          sale_price: number | null;
          condition: 'new' | 'like_new' | 'used' | 'good' | 'fair';
          category: string;
          product_code: string;
          status: 'available' | 'reserved' | 'sold';
          metadata: Record<string, any>;
          is_published: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['products']['Insert']>;
      };
      product_images: {
        Row: {
          id: string;
          product_id: string;
          image_url: string;
          sort_order: number;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['product_images']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['product_images']['Insert']>;
      };
      offers: {
        Row: {
          id: string;
          product_id: string;
          name: string;
          phone: string;
          offer_price: number;
          notes: string | null;
          status: 'pending' | 'accepted' | 'rejected' | 'countered';
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['offers']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['offers']['Insert']>;
      };
      product_notifications: {
        Row: {
          id: string;
          product_id: string;
          customer_name: string;
          phone: string | null;
          email: string | null;
          notified: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['product_notifications']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['product_notifications']['Insert']>;
      };
      settings: {
        Row: {
          id: string;
          whatsapp_number: string;
          store_name: string;
          currency: string;
          delivery_info: string | null;
          about_page: string | null;
          free_delivery_threshold: number;
          discount_150_threshold: number;
          discount_200_threshold: number;
          delivery_charge: number;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['settings']['Row'], 'id' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['settings']['Insert']>;
      };
    };
  };
};

